In [2]:
import os
import requests
import pandas as pd
import json

Create fetch_tckmstr_data

In [ ]:
# # Investigate using API
# # This only return results from page 0

# base_url = 'https://app.ticketmaster.com/discovery/v2/events.json'
# params = {
#     'apikey': 'Yn7rF52hOv8TYqTtjrLnrt9ycOJFD87F',
#     'city': 'Houston',
#     'stateCode': 'TX',
#     'countryCode': 'US',
#     'size': 50 , # Results per page
# }

# response = requests.get(base_url, params=params)
# data = response.json()

# # Write JSON file to investigate
# with open('test_data_pg0.json', 'w') as f:
#     pretty_json_str = json.dumps(data, indent=4)
#     f.write(pretty_json_str)
# print("Write success")

In [3]:
# Initialize
event_list = []
page_number = 0

# Fetch data
while True:
    ticketmaster_api_key = 'Yn7rF52hOv8TYqTtjrLnrt9ycOJFD87F'
    base_url = 'https://app.ticketmaster.com/discovery/v2/events.json'
    params = {
        'apikey': ticketmaster_api_key,
        'city': 'Houston',
        'stateCode': 'TX',
        'countryCode': 'US',
        'size': 50 ,
        'page' : page_number
    }

    response = requests.get(base_url, params=params)
    data = response.json()

    if 'page' in data:
        total_pages = data['page']['totalPages']
    
        if data['page']['number'] < total_pages:
            events = data['_embedded']['events']
            event_list.extend(events)
            print(f'Getting {page_number + 1} out of {total_pages} pages')

            page_number += 1

        else:
            break
    else:
        break

Getting 1 out of 20 pages
Getting 2 out of 20 pages
Getting 3 out of 20 pages
Getting 4 out of 20 pages
Getting 5 out of 20 pages
Getting 6 out of 20 pages
Getting 7 out of 20 pages
Getting 8 out of 20 pages
Getting 9 out of 20 pages
Getting 10 out of 20 pages
Getting 11 out of 20 pages
Getting 12 out of 20 pages
Getting 13 out of 20 pages
Getting 14 out of 20 pages
Getting 15 out of 20 pages
Getting 16 out of 20 pages
Getting 17 out of 20 pages
Getting 18 out of 20 pages
Getting 19 out of 20 pages
Getting 20 out of 20 pages

In [3]:
df = pd.DataFrame(event_list)
df.drop(columns=['locale','images','promoter','pleaseNote','products','seatmap','test','accessibility','ticketLimit','ticketing','_links', 'doorsTimes', 'outlets', 'description','ageRestrictions'], inplace=True)
df

,name,type,id,url,sales,dates,classifications,promoters,info,priceRanges,_embedded
0,Houston Texans vs. New Orleans Saints,event,G5dIZ9twBIfLn,https://www.ticketmaster.com/houston-texans-vs...,{'public': {'startDateTime': '2023-05-12T00:00...,"{'start': {'localDate': '2023-10-15', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '705', 'name': 'NFL REGULAR SEASON', '...",Please be aware that this event is subject to ...,"[{'type': 'standard', 'currency': 'USD', 'min'...","{'venues': [{'name': 'NRG Stadium', 'type': 'v..."
1,Monster Jam,event,G5dIZ9c9Oa6B6,https://www.ticketmaster.com/monster-jam-houst...,{'public': {'startDateTime': '2023-08-15T15:00...,"{'start': {'localDate': '2023-10-21', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '2515', 'name': 'FELD MOTORSPORTS', 'd...",Experience full-throttle family fun at Monster...,"[{'type': 'standard', 'currency': 'USD', 'min'...","{'venues': [{'name': 'NRG Stadium', 'type': 'v..."
2,Houston Texans vs. Tampa Bay Buccaneers,event,G5dIZ9twBlfLM,https://www.ticketmaster.com/houston-texans-vs...,{'public': {'startDateTime': '2023-05-12T00:00...,"{'start': {'localDate': '2023-11-05', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '705', 'name': 'NFL REGULAR SEASON', '...",Please be aware that this event is subject to ...,"[{'type': 'standard', 'currency': 'USD', 'min'...","{'venues': [{'name': 'NRG Stadium', 'type': 'v..."
3,Houston Texans vs. Denver Broncos,event,G5dIZ9twBEfLh,https://www.ticketmaster.com/houston-texans-vs...,{'public': {'startDateTime': '2023-05-12T00:00...,"{'start': {'localDate': '2023-12-03', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '705', 'name': 'NFL REGULAR SEASON', '...",Please be aware that this event is subject to ...,"[{'type': 'standard', 'currency': 'USD', 'min'...","{'venues': [{'name': 'NRG Stadium', 'type': 'v..."
4,Houston Texans vs. Arizona Cardinals,event,G5dIZ9twBPfL1,https://www.ticketmaster.com/houston-texans-vs...,{'public': {'startDateTime': '2023-05-12T00:00...,"{'start': {'localDate': '2023-11-19', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '705', 'name': 'NFL REGULAR SEASON', '...",Please be aware that this event is subject to ...,"[{'type': 'standard', 'currency': 'USD', 'min'...","{'venues': [{'name': 'NRG Stadium', 'type': 'v..."
...,...,...,...,...,...,...,...,...,...,...,...
946,Seong Jin Cho,event,Z7r9jZ1AdP6FS,https://www.ticketmaster.com/event/Z7r9jZ1AdP6FS,{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2023-10-08', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,"{'venues': [{'name': 'Jones Hall', 'type': 've..."
947,Raiders of the Lost Ark: Live in Concert w/ Ho...,event,Z7r9jZ1AdPF7p,https://www.ticketmaster.com/event/Z7r9jZ1AdPF7p,{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2023-11-04', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,"{'venues': [{'name': 'Jones Hall', 'type': 've..."
948,A Very Merry Pops w/ Mandy Gonzalez,event,Z7r9jZ1AdPaAo,https://www.ticketmaster.com/event/Z7r9jZ1AdPaAo,{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2023-12-22', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,"{'venues': [{'name': 'Jones Hall', 'type': 've..."
949,A Very Merry Pops w/ Mandy Gonzalez,event,Z7r9jZ1AdPaAp,https://www.ticketmaster.com/event/Z7r9jZ1AdPaAp,{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2023-12-23', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,"{'venues': [{'name': 'Jones Hall', 'type': 've..."
950,Ocie Elliott,event,Z7r9jZ1AdxvFK,https://www.ticketmaster.com/event/Z7r9jZ1AdxvFK,{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2024-01-19', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,"{'venues': [{'name': 'Heights Theater', 'type'..."

Create transform()

In [9]:
def flatten_json(y):
        out = {}
        def flatten(x, name=''):
            if type(x) is dict:
                for a in x:
                    flatten(x[a], name + a + '_')
            elif type(x) is list:
                i = 0
                for a in x:
                    flatten(a, name + str(i) + '_')
                    i += 1
            else:
                out[name[:-1]] = x
        flatten(y)
        return out

In [10]:
def flatten_data(df, col):
    flattened_col = df[col].apply(flatten_json)
    flattened_df = pd.DataFrame.from_records(flattened_col)
    
    return flattened_df

In [11]:
df_root = df.drop(columns=['sales','dates','classifications','promoters','priceRanges','_embedded'], inplace=False)
display(df_root.head(3))

,name,type,id,url,info
0,Houston Texans vs. New Orleans Saints,event,G5dIZ9twBIfLn,https://www.ticketmaster.com/houston-texans-vs...,Please be aware that this event is subject to ...
1,Monster Jam,event,G5dIZ9c9Oa6B6,https://www.ticketmaster.com/monster-jam-houst...,Experience full-throttle family fun at Monster...
2,Houston Texans vs. Tampa Bay Buccaneers,event,G5dIZ9twBlfLM,https://www.ticketmaster.com/houston-texans-vs...,Please be aware that this event is subject to ...

In [12]:
col_list = ['sales','dates','classifications','promoters','priceRanges','_embedded']
data_frames = []

for col in col_list:
    data_frame = flatten_data(df, col)
    data_frames.append(data_frame)
    
concat_df = pd.concat(data_frames, axis=1)
display(concat_df.head(3))

,public_startDateTime,public_startTBD,public_startTBA,public_endDateTime,presales_0_startDateTime,presales_0_endDateTime,presales_0_name,presales_1_startDateTime,presales_1_endDateTime,presales_1_name,...,attractions_2_upcomingEvents_mfx-ch,attractions_3_upcomingEvents_ticketweb,attractions_1_upcomingEvents_mfx-cz,attractions_1_upcomingEvents_mfx-pl,attractions_0_aliases_7,attractions_0_aliases_8,venues_0_upcomingEvents_ticketweb,attractions_1_upcomingEvents_universe,attractions_4_externalLinks_twitter_0_url,attractions_0_upcomingEvents_veeps
0,2023-05-12T00:00:00Z,False,False,2023-10-15T19:00:00Z,2023-05-12T00:00:00Z,2023-05-12T01:00:00Z,Season Ticket Member Offer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-08-15T15:00:00Z,False,False,2023-10-22T00:30:00Z,2023-08-08T15:00:00Z,2023-08-15T04:59:00Z,Feld Preferred Presale,2023-08-10T15:00:00Z,2023-08-15T04:59:00Z,TM/Venue Presale,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-05-12T00:00:00Z,False,False,2023-11-05T20:00:00Z,2023-05-12T00:00:00Z,2023-05-12T01:00:00Z,Season Ticket Member Offer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
flatten_data(df, 'sales').head(3)

,public_startDateTime,public_startTBD,public_startTBA,public_endDateTime,presales_0_startDateTime,presales_0_endDateTime,presales_0_name,presales_1_startDateTime,presales_1_endDateTime,presales_1_name,...,presales_11_name,presales_12_startDateTime,presales_12_endDateTime,presales_12_name,presales_13_startDateTime,presales_13_endDateTime,presales_13_name,presales_0_description,presales_2_description,presales_0_url
0,2023-05-12T00:00:00Z,False,False,2023-10-15T19:00:00Z,2023-05-12T00:00:00Z,2023-05-12T01:00:00Z,Season Ticket Member Offer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-08-15T15:00:00Z,False,False,2023-10-22T00:30:00Z,2023-08-08T15:00:00Z,2023-08-15T04:59:00Z,Feld Preferred Presale,2023-08-10T15:00:00Z,2023-08-15T04:59:00Z,TM/Venue Presale,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-05-12T00:00:00Z,False,False,2023-11-05T20:00:00Z,2023-05-12T00:00:00Z,2023-05-12T01:00:00Z,Season Ticket Member Offer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
flatten_data(df, 'dates').head(3)

In [ ]:
flatten_data(df, 'classifications')

In [ ]:
flatten_data(df, 'classifications')['']

In [ ]:
flatten_data(df, 'priceRanges')['']

In [ ]:
flatten_data(df, 'promoters')['']

In [ ]:
flatten_data(df, '_embedded').head(3)

In [18]:
def transform(df, cols_to_flatten):
    df_root = df.drop(columns=cols_to_flatten, inplace=False)
    
    flattened_dfs = []

    for col in cols_to_flatten:
        flattened_col = df[col].apply(flatten_json)
        flattened_df = pd.DataFrame.from_records(flattened_col)
        flattened_dfs.append(flattened_df)

    concat_df = pd.concat(flattened_dfs, axis=1)
    merged_df = pd.concat([df_root, concat_df], axis=1)
    
    return merged_df

In [19]:
trans_df = transform(df, ['sales','dates','classifications','promoters','priceRanges','_embedded']).head(3)
display(trans_df)

,name,type,id,url,info,public_startDateTime,public_startTBD,public_startTBA,public_endDateTime,presales_0_startDateTime,...,attractions_2_upcomingEvents_mfx-ch,attractions_3_upcomingEvents_ticketweb,attractions_1_upcomingEvents_mfx-cz,attractions_1_upcomingEvents_mfx-pl,attractions_0_aliases_7,attractions_0_aliases_8,venues_0_upcomingEvents_ticketweb,attractions_1_upcomingEvents_universe,attractions_4_externalLinks_twitter_0_url,attractions_0_upcomingEvents_veeps
0,Houston Texans vs. New Orleans Saints,event,G5dIZ9twBIfLn,https://www.ticketmaster.com/houston-texans-vs...,Please be aware that this event is subject to ...,2023-05-12T00:00:00Z,False,False,2023-10-15T19:00:00Z,2023-05-12T00:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Monster Jam,event,G5dIZ9c9Oa6B6,https://www.ticketmaster.com/monster-jam-houst...,Experience full-throttle family fun at Monster...,2023-08-15T15:00:00Z,False,False,2023-10-22T00:30:00Z,2023-08-08T15:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Houston Texans vs. Tampa Bay Buccaneers,event,G5dIZ9twBlfLM,https://www.ticketmaster.com/houston-texans-vs...,Please be aware that this event is subject to ...,2023-05-12T00:00:00Z,False,False,2023-11-05T20:00:00Z,2023-05-12T00:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
trans_df.columns.duplicated()

Create finalize(df)

In [20]:
condition = '^[1-9]_|_[2-9]_|_[1-9][0-9]_|.*image|.*inks|.*upcoming|attractions.*classifications|.*arking|box.?ffice|.*arket|.*dma|.*ada|.*lias|test|.*TB[A-D]|.*ocale|.*eneral.?nfo|.*ocial|.*ccessible.*eating'
col_ind = trans_df.filter(regex=condition).columns
trans_df.drop(columns=col_ind, inplace=True)

In [21]:
new_col = trans_df.rename(columns={'' : 'blank'}).columns.str.replace('0_', 'temp_').to_list()

In [22]:
trans_df.set_axis(new_col, axis=1)

,name,type,id,url,info,public_startDateTime,public_endDateTime,presales_temp_startDateTime,presales_temp_endDateTime,presales_temp_name,...,venues_temp_location_latitude,attractions_temp_name,attractions_temp_type,attractions_temp_id,attractions_temp_url,attractions_1_name,attractions_1_type,attractions_1_id,attractions_1_url,venues_temp_address_line2
0,Houston Texans vs. New Orleans Saints,event,G5dIZ9twBIfLn,https://www.ticketmaster.com/houston-texans-vs...,Please be aware that this event is subject to ...,2023-05-12T00:00:00Z,2023-10-15T19:00:00Z,2023-05-12T00:00:00Z,2023-05-12T01:00:00Z,Season Ticket Member Offer,...,29.684885,Houston Texans,attraction,K8vZ91756Kf,https://www.ticketmaster.com/houston-texans-ti...,New Orleans Saints,attraction,K8vZ9171ouV,https://www.ticketmaster.com/new-orleans-saint...,NaN
1,Monster Jam,event,G5dIZ9c9Oa6B6,https://www.ticketmaster.com/monster-jam-houst...,Experience full-throttle family fun at Monster...,2023-08-15T15:00:00Z,2023-10-22T00:30:00Z,2023-08-08T15:00:00Z,2023-08-15T04:59:00Z,Feld Preferred Presale,...,29.684885,Monster Jam,attraction,K8vZ917uyff,https://www.ticketmaster.com/monster-jam-ticke...,NaN,NaN,NaN,NaN,NaN
2,Houston Texans vs. Tampa Bay Buccaneers,event,G5dIZ9twBlfLM,https://www.ticketmaster.com/houston-texans-vs...,Please be aware that this event is subject to ...,2023-05-12T00:00:00Z,2023-11-05T20:00:00Z,2023-05-12T00:00:00Z,2023-05-12T01:00:00Z,Season Ticket Member Offer,...,29.684885,Houston Texans,attraction,K8vZ91756Kf,https://www.ticketmaster.com/houston-texans-ti...,Tampa Bay Buccaneers,attraction,K8vZ9171oCV,https://www.ticketmaster.com/tampa-bay-buccane...,NaN